### ISSUE TITLE
Pressing enter on message does not send

### ISSUE THREAD

**Issue by mattford** [mattford/scoutlink#12]
A common feature in messaging apps is that the enter button sends the message. I plan to add this feature to SL app but by default it will be disabled, with a configuration option to turn it off/on

**Comment by JordanMussi** [comment]
Why would you need it disabled by default? You can't have new lines on IRC messages IIRC (most of the time they are just split into a new message).

**Comment by mattford** [comment]
You're correct, in that case a simple case of binding the enter button to send

**Comment by mattford** [comment]
Fixed in 2.1
