### ISSUE TITLE
Viewpagerindicator vs Tablayout

### ISSUE THREAD

**Issue by DavidGMc** [mattford/scoutlink#22]
Hola.. Quiero útilizar el código de este proyecto para mi app IRC.
Me gustaría que tuviera el cambio siguiente. 
Reemplazar la visualización de Canales usando TabLayout en vez de Viewpager indicator. 
Para una mejor interfaz y que se pueda ejecutar y ver los comandos en la pestaña actual.. Tal como sucede con indicator. 
Gracias. Desde Colombia.. Perdonen el idioma y si es posible poder colaborar con mucho gusto

**Comment by mattford** [comment]
Hi David,

Thanks for the suggestion. I chose to use the VPI at the time as the app is heavily based on YAAIC IRC client. The newest version of the app (which I'm about to tag and release to alpha) replaces this entirely with a DrawerLayout which is more in line with other messaging apps such as Slack and Discord

Thanks for your interest.
