### ISSUE TITLE
Add ability to block private messages from a specific user

### ISSUE THREAD

**Issue by DavidGMc** [mattford/scoutlink#23]
Quisiera ver una opción en el menu para el usuario de poder bloquear los privados de un usuario particular . Ya sean registrados o no así como se usa el op.. Deop etc

**Comment by mattford** [comment]
Hi David,

Thanks for raising this and apologies it has taken me so long to get back to you. I'm not quite sure what you mean by an option to block the privacy of a user?

I had to put your text through google translate as I don't speak Spanish so it may have been lost in translation.

Thanks

**Comment by DavidGMc** [comment]
Ok .. Friend thank you very much for contacting me, I am closely following
your repository in github scoutlink android, since I also want to build my
app based on your code for my server.  Well what I wanted to tell you was
the possibility that as a user you have the possibility to block private
messages (ignore command), as an option in the configuration and I take
this opportunity to tell you if it is also possible that the phone vibrates
when Nick is mentioned ..  Thank you very much for your attention

**Comment by mattford** [comment]
Ah I see, that's a very good suggestion actually and one that would be quite useful for our use case.

I'll aim to include this in a future update, and I'll create a separate issue to vibrate on nick mention

**Comment by mattford** [comment]
Added in https://github.com/mattford/scoutlink/commit/8cc3b8037c76c812e2a3f5f7a4dcdb4ec38b3be8

May need some polishing
