### ISSUE TITLE
Nick autocomplete

### ISSUE THREAD

**Issue by DavidGMc** [mattford/scoutlink#26]
Nick autocomplete Hello dear friend, it would be a very good idea also to autocomplete a nickname while writing before sending the message, it is difficult to write some nicks to name them in the room

**Comment by mattford** [comment]
Implemented in https://github.com/mattford/scoutlink/commit/fea4b95197d655b3981c9c3b06359e226fc64f5f

Will be in v2.1

**Comment by DavidGMc** [comment]
Thanks Mattford, you do excellent work .. Few try to continue with an open project, naming the nicknames makes things much easier
