### ISSUE TITLE
Connection in version android 5.1 lollipop 

### ISSUE THREAD

**Issue by DavidGMc** [mattford/scoutlink#28]
Connection in version android 5.1 lollipop.  Execute the new fixes of the app, I have a cell phone with android 5.1 elg version and when connecting, I do not enter the network ... it remains in the state of "connecting to. Scoutlink ......" the other versions if I can  get in.  Greetings excellent work the best version of yaaic

**Comment by mattford** [comment]
@DavidGMc can you confirm if the same or similar happens with the old version of the app?

**Comment by DavidGMc** [comment]
Hello, With the previous version of the app I did not have that problem, it worked perfectly

**Comment by mattford** [comment]
@DavidGMc This is potentially fixed in version 2.0.1/2.1

**Comment by DavidGMc** [comment]
@mattford I just executed the code using a cell phone with Version 5.1 and it already runs great, with good stability, problem solved, excellent.

**Comment by mattford** [comment]
@DavidGMc good to hear, it was because of Java 8 APIs used by pircbotx lib :)
