### ISSUE TITLE
Add ability to define command aliases

### ISSUE THREAD

**Issue by Principe7** [mattford/scoutlink#30]
Hello @mattford 

I wanted to ask you 2 shorter things.

1) If the application can be installed on Iphone phones.

2) If the app could as a future possibility, enable the option to install scripts.

Thanks for your time.

**Comment by mattford** [comment]
No plans to create an iPhone version as I don't have the necessary hardware at the present, and I believe there is a significant ongoing cost to publishing on the App store.

Will consider adding the ability to define aliases and such

**Comment by Principe7** [comment]
Thanks Matt !!

**Comment by mattford** [comment]
`/(?>^|[^\\])(\$[0-9]+)/gm`

**Comment by mattford** [comment]
`/join` with no args crashes. It would be good to bring "hardcoded" commands and aliases under one engine which will intelligently ask for params, or at least show a message when not enough args are given

**Comment by mattford** [comment]
Merged to v2.1 - b02941c55f7ebc8002e7e7e5cd821fcc04145dc5
