### ISSUE TITLE
Support sending coloured messages

### ISSUE THREAD

**Issue by Principe7** [mattford/scoutlink#31]
Hello @mattford 

I wanted to ask you if you could add the option to write in colors only letters (without backgrounds) and a menu of emoticons.

Thanks again.

Hug !!

**Comment by mattford** [comment]
Thanks for this suggestion, the app should handle incoming coloured messages but it would be good to be able to send in colour too

**Comment by Principe7** [comment]
If it seems to me, it would help the app to have more variables also containing its own emoticons.

Hug and thanks.

**Comment by DavidGMc** [comment]
Good suggestion .. In fact you could write in color even with a background color as you would with mirc, perhaps with the help of a library

**Comment by mattford** [comment]
It appears that a lot of Android keyboards include emoji support, and the app will deal with these correctly when sending and receiving them. So I will leave that task to the keyboards.

I will aim to add coloured text support though
