### ISSUE TITLE
Private generated on sight

### ISSUE THREAD

**Issue by Genius-9** [mattford/scoutlink#32]
Good Ford

I have seen your app seems really very good, I have seen that the rooms appear in a kind of side menu on the left, there are the private ones that the user receives. I ask you and I suggest if you could make a small modification and that the private ones that the app user receives are possessed next to the name of the current channel to the right of it, I mean that the received requests do not go to the side menu of the rooms , but that it appears next to the name of the current room that we are, since there is room for that to happen, it would make a more comfortable interface and it would help people to visualize quickly when they send them a private without opening the menu of the rooms . Thanks for reading me.

**Comment by mattford** [comment]
Not quite sure how this would look/function to be honest, might need a mockup to understand

**Comment by mattford** [comment]
Not planning to change this UI at the mo
