### ISSUE TITLE
Video call option and send audio

### ISSUE THREAD

**Issue by Genius-9** [mattford/scoutlink#34]
200/5000
There is the possibility that the app can contain video call options and send voice notes, that is, audio messages, this is highly sought after by today's users. Thanks for reading and answering.

**Comment by mattford** [comment]
Going to close this one off for now as this functionality is not planned, I'm sure it could be accomplished using DCC chat but we have the SL Teamspeak for audio chat

Video can't be done using IRC and would probably open up a can of worms in terms of child protection.

Thanks for your interest
