### ISSUE TITLE
Vibration when mentioning your Nick and in private

### ISSUE THREAD

**Issue by DavidGMc** [mattford/scoutlink#40]
Vibration when mentioning your Nick and in private.  Well the new interface warns by number when you have a new private message, but you must see the side menu to realize it, it would be a very good option that when you receive a private message or when your nickname is mentioned in the room, the cell phone will vibrate and show on the  notification bar, so we would be attentive to new messages, as was the old version of yaaic.

**Comment by mattford** [comment]
Thanks @DavidGMc I already have this in the issues list: #25 

I had to roll back some of the changes to the notification because it was causing issues in some versions of android IIRC. I would like to put them back though
