### ISSUE TITLE
Nicks in colors

### ISSUE THREAD

**Issue by DavidGMc** [mattford/scoutlink#46]
It would be good to implement that user Nicknames appear in colors, like the yaaic version and are reflected in the chat bubbles,
More than a problem, it is an alternative

**Comment by mattford** [comment]
How would the colour be determined? Is it user defined?

**Comment by DavidGMc** [comment]
> ¿Cómo se determinaría el color? ¿Está definido por el usuario?

Interesting point, perhaps the user can define the color of his Nick or if not also let the system do it by itself.  You can choose either of the two options, in my case I prefer the user to do it himself

**Comment by mattford** [comment]
Can you attach a screenshot of how this looks?

**Comment by mattford** [comment]
Not sure how this would work or if it would be useful so closing for now

**Comment by DavidGMc** [comment]
ok .. maybe another time, it was just that the nicknames were seen in colors, automatically by the system
