### ISSUE TITLE
password in the application login

### ISSUE THREAD

**Issue by DavidGMc** [mattford/scoutlink#53]
What is the possibility of putting in login (MainActivity) that the user enters with his nickname, but if he is registered, the possibility also to enter at the same time with his password (nickserv password) and not do it from the configurations.

**Comment by mattford** [comment]
@DavidGMc That would be possible to do, however it would not be possible to check before connecting whether the nickname is registered, and the presence of the password field may confuse new users.

I'll have a think about what could be done.

**Comment by DavidGMc** [comment]
Ok we'll see what can be done ..

**Comment by DavidGMc** [comment]
Fixed login with commands on startup in settings
