### ISSUE TITLE
channel event configuration as user input and output

### ISSUE THREAD

**Issue by DavidGMc** [mattford/scoutlink#54]
hide or make visible the inputs and outputs of the users in the application, maybe add it in the settings.

**Comment by mattford** [comment]
Not 100% sure what you mean, can you give an example?

**Comment by DavidGMc** [comment]
If, for example, an option in the configuration that says entry and exit of nicknames, perhaps a checkbox that if enabled, the nicknames that enter the server will be seen in the chat, otherwise it will not show who enters, as in the old version of yaaic.

**Comment by DavidGMc** [comment]
Example
![Screenshot_20211009-125058_1](https://user-images.githubusercontent.com/23423226/136669283-f5af0f01-3868-4e74-8c20-cb48d414239f.jpg)
