### ISSUE TITLE
Channel list forces landscape and crashes app

### ISSUE THREAD

**Issue by kenrachynski** [mattford/scoutlink#8]
I was trying out the app today on a Toshiba tablet running Android 4.1.1. I think the native orientation for this device is landscape and I was using it in portrait. Once connected, the channel list popped up switching the display to landscape on me. As soon as I picked a channel to chat in, I got the message that this app had unfortunately stopped. 

I'm not sure if its the age of the device or the OS that's a factor or thus us just a bug.

**Comment by mattford** [comment]
Fixed in next release. This happened because a change of orientation actually restarts the Activity, meaning the reference to the IRC connect is lost briefly, which causes the app to crash when it tries to join a channel
