### ISSUE TITLE
No clear indication of notices

### ISSUE THREAD

**Issue by kenrachynski** [mattford/scoutlink#9]
Not being on my usual system, I logged in under a guest name. I used /nick to switch to my Nick and started chatting. I didn't notice anything odd until I got renamed to a Guest_\* nick. 

Nickserv's messages to me ended up on the ScoutLink tab while I looked at #english. There was no indication that new data had been sent to that other tab.

**Comment by mattford** [comment]
Fixed in next release - notices will be shown in channels where the sender is present, in the active channel when the notice is received, and in the server window
